[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "cd be_poker && ./main"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on-failure"

[env]
PORT = "8080" 