# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'PokerTrackerApp' do
  config = use_native_modules!

  # 修復 Xcode Cloud 中的 Yoga 路徑問題
  ENV['INSTALL_YOGA_WITHOUT_PATH_OPTION'] = nil
  
  # 強制禁用新架構和 Fabric
  ENV['RCT_NEW_ARCH_ENABLED'] = '0'
  ENV['USE_FABRIC'] = '0'

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => false,
    :fabric_enabled => false,
    # 確保完全禁用新架構
    :new_arch_enabled => false
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    
    # 修復 Xcode Cloud 中的 PrivacyInfo.xcprivacy 問題
    installer.pods_project.targets.each do |target|
      if target.name == 'React-cxxreact'
        target.build_configurations.each do |config|
          config.build_settings['INFOPLIST_FILE'] = '$(PODS_TARGET_SRCROOT)/PrivacyInfo.xcprivacy'
        end
      end
    end
  end
end
